# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ec2-client-vpn
  description: This component is responsible for provisioning VPN Client Endpoints
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component






